apiVersion: cloud-build-notifiers/v1
kind: SlackNotifier
metadata:
  name: cloudbuild-slack-notifier
spec:
  notification:
    filter: build.status == Build.Status.SUCCESS
    params:
      buildStatus: $(build.status)
    delivery:
      webhookUrl:
        secretRef: webhook-url
    template:
      type: golang
      uri: gs://myrecord-376903-notifiers-config/slack-template.json
  secrets:
  - name: webhook-url
    value: projects/myrecord-376903/secrets/SLACK_WEBHOOK_URL_FOR_BUILD/versions/latest
