name: update-cloud-storage
run-name: ${{ github.actor }} is update slack config
on:
  push:
    branches:
      - main
jobs:
  upload-files:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'myrecord-376903-notifiers-config'
        destination: 'myrecord-376903-notifiers-config'
        parent: false